language: bash
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/deps

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q git automake libcppunit-dev libtool build-essential pkg-config libssl-dev libncurses5-dev

install:
  - sudo cp rtorrent-launcher.sh /etc/init.d/rtorrent
  - sudo chmod +x /etc/init.d/rtorrent
  - sudo update-rc.d rtorrent defaults
  - sudo cp rtorrent-launcher.conf /etc/
  - sudo cp .rtorrent.rc $HOME/
  - sudo chmod +x travis/*
  - sudo bash -e travis/install-xmlrpc.sh
  - sudo bash -e travis/install-libsigcpp.sh
  - sudo bash -e travis/install-cares.sh
  - sudo bash -e travis/install-curl.sh
  - sudo bash -e travis/install-libtorrent.sh
  - sudo bash -e travis/install-rtorrent.sh

before_script:
  - sudo mkdir $HOME/.rtorrent.session /var/log/rtorrent
  - sudo chown -R $USER. $HOME /var/log/rtorrent/
  - sudo sed "s/USER=\"rotrrent\"/USER=\"$USER\"/" -i /etc/rtorrent-launcher.conf
  - sudo sed "s/RTORRENT_CONFIG=\"\/home\/rtorrent\/.rtorrent.rc\"/RTORRENT_CONFIG=\"$HOME\/.rtorrent.rc\"/" -i /etc/rtorrent-launcher.conf
  - sudo cat /etc/rtorrent-launcher.conf

script: bash -e travis/run.sh

after_script:
  - ls -al $HOME/.rtorrent.session/
  - cat /var/log/rtorrent/rtorrent-launcher.log

notifications:
  slack:
    secure: Q5z9SE+a6BOfiJQpZbGrIloPayObtmEtKYDRwBYQwi5TJiCCt3G4RtvnBHy36DUL+CoNHxeHLCFU5cr2wW/Adu6TR9XoPgr08EIc9oqLiTrQONgDgwGqdk4NrqFLfg0UWVPgDLtfqE7nuAHGRdIeF9zHJX5Xe8xve3yhSsRY5FSoQv8ab0i1SKWSqFsV9JaQdSLyboeJRJv8p6RHt5ayxXY3gBh74qFbK7TGQcJhqhz0i+1CPIujFL6lp6sl8xI0cqx+mTf04mWjv+wovjjtl5c5aAKRhIC9ApT2AcvM8SZ0xxZ6TNsrwb9Wdc3QHH9fLUsDqKr5X+orHVJKQZ4e8i8SkloBDDLiiNRsArLpgzVRxrZ4NdFK+KRBFl26PkuN7k+2vdcpP0dtlKOdZy/ON0ENzt1vK2RGx4SUEGiD8y0VImElZ8doblTc41WKtPUmMn0zz20st/UUbH2vaoV4YpSWf6DbDBgNkCD2hoM8GiHAgnWHIkv1X+RQDXjep+OAfUPp7dEgNZ8e0J8muVbOAJuwevwHMj0Z+uqqnzvXKGgaFL4iq4K1hr9LHn3WM/wFQ9fNce4s3+Shbgi9mwk6sSsl2KDSLL2+0sUF7lkp8VZDQZ5+kLt/qOwRPS/eJvXOLtoyeJ9adZbSzl0weZ574G1mIBCImQCKJf15y+dih5o=
