language: bash
sudo: required
dist: trusty

cache:
  directories:
    - $HOME/deps

before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q git automake libcppunit-dev libtool build-essential pkg-config libssl-dev libncurses5-dev

install:
  - sudo cp rtorrent-launcher.sh /etc/init.d/rtorrent
  - sudo chmod +x /etc/init.d/rtorrent
  - sudo update-rc.d rtorrent defaults
  - sudo cp rtorrent-launcher.conf /etc/
  - sudo cp travis/.rtorrent.rc /home/$USER/
  - sudo chmod +x travis/*.sh
  - sudo bash -e travis/install-xmlrpc.sh
  - sudo bash -e travis/install-libsigcpp.sh
  - sudo bash -e travis/install-cares.sh
  - sudo bash -e travis/install-curl.sh
  - sudo bash -e travis/install-libtorrent.sh
  - sudo bash -e travis/install-rtorrent.sh

before_script:
  - sudo mkdir /home/$USER/.rtorrent.session /var/log/rtorrent
  - sudo chown -R $USER. /home/$USER/ /var/log/rtorrent/
  - sudo sed "s/USER=\"rtorrent\"/USER=\"$USER\"/" -i /etc/rtorrent-launcher.conf
  - sudo sed "s/RTORRENT_CONFIG=\"\/home\/rtorrent\/.rtorrent.rc\"/RTORRENT_CONFIG=\"\/home\/$USER\/.rtorrent.rc\"/" -i /etc/rtorrent-launcher.conf
  - sudo sed "s/session = ~\/.rtorrent.session/session = \/home\/$USER\/.rtorrent.session/" -i /home/$USER/.rtorrent.rc
  - sudo cat /etc/rtorrent-launcher.conf

script: bash -e travis/run.sh

after_script:
  - ls -al /home/$USER/.rtorrent.session/
  - cat /var/log/rtorrent/rtorrent-launcher.log
  - cat /var/log/rtorrent/rtorrent.log
